from os import path

# paths as seen from main.py

UPLOADS_FOLDER = 'UPLOADS'

UPLOADED_BOOKS_FOLDER = path.join(UPLOADS_FOLDER, 'BOOKS')
UPLOADED_COVER_PAGES_FOLDER = path.join(UPLOADS_FOLDER, 'COVER_PAGES')

# USER CONSTANTS
MAX_USER_NAME_LENGTH = 24

# BOOK CONSTANTS
MAX_BOOK_NAME_LENGTH = 150
MAX_BOOK_DESCRIPTION_LENGTH = 500
BOOK_SAVE_NAME_LENGTH = 50

# GROUP CONSTANTS
MAX_GROUP_NAME_LENGTH = 24

# OTHER CONSTANTS


# PRUEBAS
